import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { OrderStatus, UserRole } from '@lunara/types';
import { Order, OrderDocument } from '../orders/schemas/order.schema';
import { Branch, BranchDocument } from '../branches/schemas/branch.schema';
import { User, UserDocument } from '../users/schemas/user.schema';
import { SettingsService } from '../settings/settings.service';
import { RiderAssignmentService } from '../riders/rider-assignment.service';
import { PartnerOperationsService } from '../partner/partner-operations.service';

/**
 * Periodic sweep that performs the automations an admin has toggled on in Automation Settings.
 * Every check re-reads the flag from settingsService so toggling off takes effect on the next run
 * without a redeploy, and each action mirrors exactly what the manual admin endpoint already does.
 */
@Injectable()
export class AutomationSchedulerService {
  private readonly logger = new Logger(AutomationSchedulerService.name);

  constructor(
    @InjectModel(Order.name) private orderModel: Model<OrderDocument>,
    @InjectModel(Branch.name) private branchModel: Model<BranchDocument>,
    @InjectModel(User.name) private userModel: Model<UserDocument>,
    private settingsService: SettingsService,
    private riderAssignmentService: RiderAssignmentService,
    private partnerOperationsService: PartnerOperationsService,
  ) {}

  @Cron(CronExpression.EVERY_MINUTE)
  async sweepRiderAssignments() {
    const [autoPickup, autoDelivery] = await Promise.all([
      this.settingsService.isAutomationEnabled('autoAssignPickupRider'),
      this.settingsService.isAutomationEnabled('autoAssignDeliveryRider'),
    ]);

    if (autoPickup) {
      const pending = await this.orderModel
        .find({
          dispatchStatus: 'dispatched',
          partnerAcceptedAt: { $exists: true },
          pickupRiderId: { $exists: false },
          status: { $in: [OrderStatus.SHOP_ASSIGNED, OrderStatus.CONFIRMED] },
        })
        .limit(25);

      for (const order of pending) {
        try {
          await this.riderAssignmentService.confirmSuggestedPickupRider(order._id.toString(), '');
        } catch (err) {
          this.logger.warn(`Auto pickup-rider assignment skipped for order ${order._id}: ${(err as Error).message}`);
        }
      }
    }

    if (autoDelivery) {
      const pending = await this.orderModel
        .find({ status: OrderStatus.READY_FOR_DELIVERY, deliveryRiderId: { $exists: false } })
        .limit(25);

      for (const order of pending) {
        try {
          await this.riderAssignmentService.confirmSuggestedDeliveryRider(order._id.toString(), '');
        } catch (err) {
          this.logger.warn(`Auto delivery-rider assignment skipped for order ${order._id}: ${(err as Error).message}`);
        }
      }
    }
  }

  /** Weekly settlement generation for every partner branch with unsettled completed orders. */
  @Cron(CronExpression.EVERY_WEEK)
  async generateScheduledSettlements() {
    if (!(await this.settingsService.isAutomationEnabled('autoGenerateSettlements'))) return;

    const systemAdmin = await this.userModel.findOne({ role: UserRole.ADMIN });
    if (!systemAdmin) {
      this.logger.warn('Auto-settlement skipped: no admin user found to attribute settlements to');
      return;
    }

    const branches = await this.branchModel.find({ branchType: 'partner_shop' });
    for (const branch of branches) {
      try {
        const unsettled = await this.partnerOperationsService.getUnsettledOrders(
          branch.partnerUserId.toString(),
        );
        const orderIds = unsettled.data.map((o) => o.orderId);
        if (orderIds.length === 0) continue;

        await this.partnerOperationsService.createSettlement(
          systemAdmin._id.toString(),
          branch.partnerUserId.toString(),
          { orderIds, adminNote: 'Auto-generated by scheduled automation' },
        );
      } catch (err) {
        this.logger.warn(`Auto-settlement skipped for branch ${branch._id}: ${(err as Error).message}`);
      }
    }
  }
}
