import { AddonCategory, BookingType, ServiceCategory } from '@lunara/types';
import type { Collection } from 'mongodb';
import { defaultAddonImageUrl, writeCatalogAddonImages } from './catalog-addon-images';

export const DEFAULT_LAUNDRY_SERVICES = [
  {
    type: BookingType.WASH_FOLD,
    label: 'Wash & Fold',
    description: 'Everyday clothes washed, dried, and folded',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 80,
    minWeightKg: 5,
    isActive: true,
    sortOrder: 1,
  },
  {
    type: BookingType.WASH_DRY_FOLD,
    label: 'Wash, Dry & Fold',
    description: 'Full service including machine dry',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 120,
    minWeightKg: 5,
    isActive: true,
    sortOrder: 2,
  },
  {
    type: BookingType.DRY_CLEANING,
    label: 'Dry Cleaning',
    description: 'Delicates, suits, and formal wear',
    category: ServiceCategory.GARMENT_CARE,
    pricePerKg: 200,
    minWeightKg: 5,
    isActive: true,
    sortOrder: 3,
  },
  {
    type: BookingType.WASH_DRY,
    label: 'Wash & Dry',
    description: 'Wash and machine dry without folding',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 100,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 4,
  },
  {
    type: BookingType.WASH_DRY_FOLD_IRON,
    label: 'Wash, Dry, Fold & Iron',
    description: 'Premium pressed finish',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 160,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 5,
  },
  {
    type: BookingType.COMFORTERS,
    label: 'Comforters & Bedding',
    description: 'Duvets, comforters, and heavy bedding',
    category: ServiceCategory.HOME_TEXTILES,
    pricePerKg: 180,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 6,
  },
  {
    type: BookingType.CURTAINS,
    label: 'Curtains',
    description: 'Home and office curtains',
    category: ServiceCategory.HOME_TEXTILES,
    pricePerKg: 220,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 7,
  },
  {
    type: BookingType.SHOES,
    label: 'Shoe Cleaning',
    description: 'Sneakers and casual footwear',
    category: ServiceCategory.FOOTWEAR_LEATHER,
    pricePerKg: 250,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 8,
  },
  {
    type: BookingType.UNIFORMS,
    label: 'Uniforms',
    description: 'School and work uniforms',
    category: ServiceCategory.GARMENT_CARE,
    pricePerKg: 90,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 9,
  },
  {
    type: BookingType.IRONING,
    label: 'Ironing / Press Only',
    description: 'Pressing only, no wash',
    category: ServiceCategory.GARMENT_CARE,
    pricePerKg: 100,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 10,
  },
  {
    type: BookingType.RUGS,
    label: 'Rugs & Carpets',
    description: 'Area rugs and carpet cleaning',
    category: ServiceCategory.HOME_TEXTILES,
    pricePerKg: 300,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 11,
  },
  {
    type: BookingType.UPHOLSTERY,
    label: 'Upholstery',
    description: 'Sofas, chairs, and furniture covers',
    category: ServiceCategory.HOME_TEXTILES,
    pricePerKg: 320,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 12,
  },
  {
    type: BookingType.BAGS,
    label: 'Bags',
    description: 'Backpacks, handbags, and luggage',
    category: ServiceCategory.FOOTWEAR_LEATHER,
    pricePerKg: 200,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 13,
  },
  {
    type: BookingType.LEATHER,
    label: 'Leather Care',
    description: 'Leather jackets, bags, and accessories',
    category: ServiceCategory.FOOTWEAR_LEATHER,
    pricePerKg: 350,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 14,
  },
  {
    type: BookingType.ALTERATION,
    label: 'Alteration & Repair',
    description: 'Hemming, resizing, and repairs',
    category: ServiceCategory.GARMENT_CARE,
    pricePerKg: 150,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 15,
  },
  {
    type: BookingType.PREMIUM_WASH_FOLD,
    label: 'Premium Wash & Fold',
    description: 'Upgraded detergents and extra care for everyday clothes',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 110,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 16,
  },
  {
    type: BookingType.BABY_CLOTHES_WASH,
    label: 'Baby Clothes Wash',
    description: 'Gentle, hypoallergenic wash for infant and toddler clothing',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 100,
    minWeightKg: 3,
    isActive: false,
    sortOrder: 17,
  },
  {
    type: BookingType.DELICATES_WASH,
    label: 'Delicates Wash',
    description: 'Gentle cycle for lingerie, silk, and other delicate fabrics',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 130,
    minWeightKg: 3,
    isActive: false,
    sortOrder: 18,
  },
  {
    type: BookingType.COLOR_SEPARATION_WASH,
    label: 'Color Separation',
    description: 'Darks and lights washed separately to prevent color bleed',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 95,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 19,
  },
  {
    type: BookingType.WHITE_GARMENTS_WASH,
    label: 'White Garments Only',
    description: 'Dedicated wash for whites, with brightening treatment',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 95,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 20,
  },
  {
    type: BookingType.HAND_WASH,
    label: 'Hand Wash',
    description: 'Hand-washed for delicate or hand-wash-only garments',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 150,
    minWeightKg: 2,
    isActive: false,
    sortOrder: 21,
  },
  {
    type: BookingType.MACHINE_WASH,
    label: 'Machine Wash',
    description: 'Standard machine wash cycle',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 80,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 22,
  },
  {
    type: BookingType.ECO_FRIENDLY_WASH,
    label: 'Eco-Friendly Wash',
    description: 'Biodegradable detergents and cold-water wash',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 100,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 23,
  },
  {
    type: BookingType.HYPOALLERGENIC_WASH,
    label: 'Hypoallergenic Wash',
    description: 'Fragrance-free detergent for sensitive skin',
    category: ServiceCategory.CORE_LAUNDRY,
    pricePerKg: 100,
    minWeightKg: 5,
    isActive: false,
    sortOrder: 24,
  },
  {
    type: BookingType.SANITIZING_DISINFECTION,
    label: 'Sanitizing & Disinfection',
    description: 'Antimicrobial wash for baby clothes, hospital uniforms, and linens',
    category: ServiceCategory.WELLNESS_SANITATION,
    pricePerKg: 140,
    minWeightKg: 3,
    isActive: false,
    sortOrder: 25,
  },
  {
    type: BookingType.WEDDING_GOWN_PRESERVATION,
    label: 'Wedding Gown Preservation',
    description: 'Specialty cleaning, vacuum packaging, and preservation box for gowns',
    category: ServiceCategory.SPECIALTY,
    pricePerKg: 500,
    minWeightKg: 1,
    isActive: false,
    sortOrder: 26,
  },
  {
    type: BookingType.SPECIALTY_ITEMS,
    label: 'Specialty Cleaning',
    description: 'Stuffed toys, pet beds, sports gear, and baby strollers',
    category: ServiceCategory.SPECIALTY,
    pricePerKg: 200,
    minWeightKg: 2,
    isActive: false,
    sortOrder: 27,
  },
];

export const DEFAULT_LAUNDRY_ADDONS = [
  {
    slug: 'fabric_softener',
    label: 'Fabric softener',
    description: 'Extra soft finish',
    category: AddonCategory.FINISHING,
    price: 25,
    isActive: true,
    sortOrder: 1,
    allowsQuantity: true,
    maxQuantity: 5,
  },
  {
    slug: 'liquid_detergent',
    label: 'Liquid detergent',
    description: 'Extra detergent for heavier or extra-dirty loads',
    category: AddonCategory.TREATMENT,
    price: 25,
    isActive: true,
    sortOrder: 2,
    allowsQuantity: true,
    maxQuantity: 5,
  },
  {
    slug: 'stain_treatment',
    label: 'Stain treatment',
    description: 'Pre-treatment for tough stains',
    category: AddonCategory.TREATMENT,
    price: 50,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'eco_wash',
    label: 'Eco wash',
    description: 'Hypoallergenic detergent',
    category: AddonCategory.TREATMENT,
    price: 30,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'express_delivery',
    label: 'Express return',
    description: 'Delivery within 24h after cleaning',
    category: AddonCategory.SPEED,
    price: 80,
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: 'express_service_24h',
    label: 'Express Service (24 Hours)',
    description: 'Rushed turnaround — ready within 24 hours',
    category: AddonCategory.SPEED,
    price: 50,
    isPercentOfService: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: 'same_day_service',
    label: 'Same-Day Service',
    description: "Ready the same day it's dropped off",
    category: AddonCategory.SPEED,
    price: 100,
    isPercentOfService: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: 'premium_stain_removal',
    label: 'Premium Stain Removal',
    description: 'Advanced treatment for tough or set-in stains',
    category: AddonCategory.TREATMENT,
    price: 100,
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: 'heavy_stain_treatment',
    label: 'Heavy Stain Treatment',
    description: 'Deep treatment for heavily soiled garments',
    category: AddonCategory.TREATMENT,
    price: 150,
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: 'odor_removal',
    label: 'Odor Removal',
    description: 'Deodorizing treatment for smoke, mildew, or other odors',
    category: AddonCategory.TREATMENT,
    price: 80,
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: 'steam_pressing',
    label: 'Steam Pressing',
    description: 'Finishing steam press for a crisp, wrinkle-free look',
    category: AddonCategory.FINISHING,
    price: 50,
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: 'waterproofing',
    label: 'Waterproofing',
    description: 'Water-repellent treatment for jackets and outerwear',
    category: AddonCategory.PROTECTION,
    price: 200,
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: 'fabric_protection',
    label: 'Fabric Protection',
    description: 'Protective coating against future stains',
    category: AddonCategory.PROTECTION,
    price: 150,
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: 'minor_repair_button',
    label: 'Minor Repair (Button)',
    description: 'Button reattachment or replacement',
    category: AddonCategory.REPAIR,
    price: 50,
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: 'minor_stitching',
    label: 'Minor Stitching',
    description: 'Small seam or hem stitching',
    category: AddonCategory.REPAIR,
    price: 80,
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: 'garment_bag_packaging',
    label: 'Garment Bag Packaging',
    description: 'Protective garment bag for delivery',
    category: AddonCategory.FINISHING,
    price: 30,
    isActive: true,
    sortOrder: 15,
  },
  {
    slug: 'premium_hanger',
    label: 'Premium Hanger',
    description: 'Upgraded hanger for delivered garments',
    category: AddonCategory.FINISHING,
    price: 20,
    isActive: true,
    sortOrder: 16,
  },
  {
    slug: 'fabric_brightening',
    label: 'Fabric Brightening & Restoration',
    description: 'Yellowing removal and color restoration for aged garments',
    category: AddonCategory.TREATMENT,
    price: 120,
    isActive: true,
    sortOrder: 17,
  },
  {
    slug: 'sanitizing_treatment',
    label: 'Sanitizing & Disinfection',
    description: 'Antimicrobial treatment for baby clothes, uniforms, and linens',
    category: AddonCategory.TREATMENT,
    price: 60,
    isActive: true,
    sortOrder: 18,
  },
  {
    slug: 'steam_sanitizing',
    label: 'Steam Sanitizing',
    description: 'High-heat steam treatment for plush toys, baby items, and pillows',
    category: AddonCategory.TREATMENT,
    price: 70,
    isActive: true,
    sortOrder: 19,
  },
  {
    slug: 'gown_preservation_packaging',
    label: 'Preservation Packaging',
    description: 'Vacuum packaging and storage box for wedding gowns and heirloom garments',
    category: AddonCategory.FINISHING,
    price: 350,
    isActive: true,
    sortOrder: 20,
  },
  {
    slug: 'shoe_sole_restoration',
    label: 'Sole Cleaning & Restoration',
    description: 'Deep clean and whitening for shoe soles',
    category: AddonCategory.TREATMENT,
    price: 90,
    isActive: true,
    sortOrder: 21,
  },
];

export async function reseedLaundryAddons(collection: Collection) {
  writeCatalogAddonImages(DEFAULT_LAUNDRY_ADDONS.map((a) => a.slug));
  const now = new Date();
  for (const addon of DEFAULT_LAUNDRY_ADDONS) {
    const imageUrl = defaultAddonImageUrl(addon.slug);
    await collection.updateOne(
      { slug: addon.slug },
      {
        $set: { ...addon, imageUrl, updatedAt: now },
        $setOnInsert: { createdAt: now },
      },
      { upsert: true },
    );
    console.log(`  ${addon.slug} — ${addon.label} (${addon.isActive ? 'active' : 'inactive'})`);
  }
}

export async function reseedLaundryServices(collection: Collection) {
  const now = new Date();
  for (const service of DEFAULT_LAUNDRY_SERVICES) {
    await collection.updateOne(
      { type: service.type },
      {
        $set: { ...service, updatedAt: now },
        $setOnInsert: { createdAt: now },
      },
      { upsert: true },
    );
    console.log(`  ${service.type} — ${service.label} (${service.isActive ? 'active' : 'inactive'})`);
  }
}
